version: "3"

services:
  backend:
    build: backend/.
    ports:
      - "3000"
    volumes:
      - .:/app
    environment:
      HOST1: ['192.168.11.80']
      HOST2: ['192.168.11.81']

  frontend:
    build: frontend/.
    