version: "3"

services:
  backend:
    build: backend/.
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/app
    environment:
      HOST1: "192.168.243.66"
      HOST2: "192.168.11.81"

  frontend:
    build: frontend/.
    ports:
      - "80:80"