version: "3"

services:
  backend:
    build: backend/.
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/app
    environment:
      HOST1: "192.168.243.66"  #defines displays to control. Comma separated list 
      HOST2: "192.168.243.101"  #defines displays to control. Comma separated list 

  frontend1:
    build: frontend/.
    ports:
      - "8081:80"
  
  frontend2:
    build: frontend/.
    ports:
      - "8082:80"