version: "3"

services:
  backend:
    build: backend/.
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/app
    environment:
      HOST1: "192.168.10.115"  #defines displays to control. Comma separated list 
      HOST2: "192.168.10.20"  #defines displays to control. Comma separated list 
    restart: always

  frontend1:
    build: frontend/.
    ports:
      - "8081:80"
    restart: always
    environment:
      MODE: "UDP"  ##defines if UDP or TCP is used

  frontend2:
    build: frontend/.
    ports:
      - "8082:80"
    restart: always
    environment:
      MODE: "UDP"  #defines if UDP or TCP is used 

